import React, { useState, useEffect } from 'react';
import { Key, ShieldCheck, ChevronRight } from 'lucide-react';

interface OtpVerificationStepProps {
  onVerifyOtp: (otpString: string) => void;
  onTriggerToast: (type: 'success' | 'error' | 'info' | 'warning', title: string, desc?: string) => void;
}

export default function OtpVerificationStep({ onVerifyOtp, onTriggerToast }: OtpVerificationStepProps) {
  const [otp, setOtp] = useState(['', '', '', '', '', '']);
  const [countdown, setCountdown] = useState(59);

  useEffect(() => {
    let timer: any = null;
    if (countdown > 0) {
      timer = setTimeout(() => setCountdown(prev => prev - 1), 1000);
    }
    return () => clearTimeout(timer);
  }, [countdown]);

  const handleOtpInput = (val: string, index: number) => {
    if (!/^\d*$/.test(val)) return;
    const nextOtp = [...otp];
    nextOtp[index] = val;
    setOtp(nextOtp);

    if (val && index < 5) {
      const nextInput = document.getElementById(`otp-${index + 1}`);
      nextInput?.focus();
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const enteredOtp = otp.join('');
    if (enteredOtp.length < 6) {
      onTriggerToast('error', '2FA Incomplete', 'Provide full 6-digit verification code.');
      return;
    }
    onVerifyOtp(enteredOtp);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-5">
      <div className="text-center space-y-2">
        <div className="w-12 h-12 rounded-full bg-brand-primary/10 text-brand-primary flex items-center justify-center mx-auto">
          <ShieldCheck size={24} />
        </div>
        <h4 className="text-sm font-bold text-brand-text-primary">Multi-Factor Authentication (OTP)</h4>
        <p className="text-xs text-brand-text-secondary">Input the 6-digit authorization passkey generated by your Authenticator app.</p>
      </div>

      <div className="flex justify-center gap-2">
        {otp.map((digit, idx) => (
          <input
            key={idx}
            id={`otp-${idx}`}
            type="text"
            maxLength={1}
            value={digit}
            onChange={(e) => handleOtpInput(e.target.value, idx)}
            className="w-10 h-11 text-center font-mono font-bold text-base border rounded border-brand-border bg-white text-brand-text-primary focus:border-brand-primary focus:outline-none"
          />
        ))}
      </div>

      <div className="flex justify-between items-center text-xs text-brand-text-secondary font-mono">
        <span>Resend in: 00:{countdown < 10 ? `0${countdown}` : countdown}</span>
        <button
          type="button"
          onClick={() => {
            setCountdown(59);
            onTriggerToast('info', 'OTP Resent', 'Fresh 2FA passkey dispatched.');
          }}
          className="text-brand-primary font-bold hover:underline cursor-pointer"
        >
          Resend Passkey
        </button>
      </div>

      <button
        type="submit"
        className="w-full py-2.5 bg-brand-primary hover:bg-blue-700 text-white font-bold text-xs rounded transition shadow-xs cursor-pointer flex items-center justify-center gap-1.5"
      >
        <Key size={14} /> Verify Passkey & Continue <ChevronRight size={14} />
      </button>
    </form>
  );
}
